# Generated by Django 6.0.1 on 2026-01-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('subject', models.CharField(choices=[('ingliz', 'Ingliz tili'), ('rus', 'Rus tili'), ('koreys', 'Koreys tili'), ('xitoy', 'Xitoy tili'), ('ona', 'Ona tili'), ('tarix', 'Tarix'), ('pochemuchka', 'Pochemuchka'), ('mental', 'Mental arifmetika'), ('kompyuter', 'Kompyuter savodxonligi'), ('backend', 'Backend dasturlash'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya')], max_length=50)),
                ('lesson_day', models.CharField(choices=[('du_ju', 'Dushanba / Juma'), ('se_pa', 'Seshanba / Payshanba'), ('sh_yn', 'Shanba / Yakshanba'), ('boshqa', 'Boshqa (admin bilan aniqlanadi)')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
