"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1
"""

from pathlib import Path

# ===============================
# 1. BASE DIR
# ===============================
BASE_DIR = Path(__file__).resolve().parent.parent


# ===============================
# 2. SECURITY
# ===============================
SECRET_KEY = 'django-insecure-^cd33=(4e$xihjk#bn&hoyth#a25@0nbo%htwz4mwoysz+5jey'

DEBUG = True

# 🔧 O'ZGARTIRILDI (bo'sh emas)
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# ===============================
# 3. APPLICATIONS
# ===============================
INSTALLED_APPS = [
    # Django standart app'lari
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party
    'rest_framework',
    'corsheaders',

    # Sizning app
    'applications',
]


# ===============================
# 4. MIDDLEWARE
# ===============================
# 🔧 O'ZGARTIRILDI (to'g'ri tartib)
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",   # 👈 ENG YUQORIDA
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ===============================
# 5. URLS
# ===============================
ROOT_URLCONF = 'config.urls'


# ===============================
# 6. TEMPLATES
# ===============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ===============================
# 7. WSGI
# ===============================
WSGI_APPLICATION = 'config.wsgi.application'


# ===============================
# 8. DATABASE
# ===============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ===============================
# 9. PASSWORD VALIDATION
# ===============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ===============================
# 10. INTERNATIONALIZATION
# ===============================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ===============================
# 11. STATIC FILES
# ===============================
# 🔧 O'ZGARTIRILDI (slash bilan)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# ===============================
# 12. MEDIA FILES
# ===============================
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ===============================
# 13. CORS & CSRF (React 5173 uchun)
# ===============================
# 🔧 O'ZGARTIRILDI (React → Django POST ishlashi uchun)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True
